#import "@/modules/claims/graphql/fragments/ClaimStatusDetailDataFragment.gql"

query ClaimStatusDetail(
  $claim: String
  $patient: String
) {
  claimStatusDetail(
    claim: $claim
    patient: $patient
  ) {
    claimStatusDetail {
      ...ClaimStatusDetailData
    }
  }
}
