#import "../fragments/SupportingDocumentDataFragment.gql"

query SupportingDocuments(
  $claim: String
  $patient: String
  $supportDocumentId: String
) {
  supportingDocuments(
    claim: $claim
    patient: $patient
    supportDocumentId: $supportDocumentId
  ) {
    ...SupportingDocumentData
  }
}
