#import "@/modules/core/graphql/fragments/PaginationFragment.gql"
#import "@/modules/core/graphql/fragments/PersonDataFragment.gql"

query AllPersons {
  personsPage(
    name: ""
    page: 1
  ) {
    persons {
      ...PersonData
    }
    pageInfo {
      ...Pagination
    }
  }
}
