#import "@/modules/core/graphql/fragments/RvsCodeDataFragment.gql"

query RvsCodes(
  $search: String
  $pageSize: Int

) {
  rvsCodes(
    search: $search
    pageSize: $pageSize
  ) {
    ...RvsCodeData
  }
}