#import "@/modules/core/graphql/fragments/PrincipalDataFragment.gql"

fragment MemberData on Member {
  id
  pin
  membershipType
  pen
  employerName
  createdAt
  updatedAt
  relation
  principalId
  principal {
    ...PrincipalData
  }
}
