#import "@/modules/core/graphql/fragments/PrincipalMemberDataFragment.gql"

fragment PrincipalData on Person {
  id
  lastName
  firstName
  middleName
  mailingAddress
  zipCode
  mobileNo
  landLineNo
  emailAddress
  birthDate
  suffix
  sex
  member {
    ...PrincipalMemberData
  }
}

