<?php

namespace Tests\Unit\Lib\Auth;

use App\Lib\Auth\Authentication;
use Tests\Concerns\InteractsWithTenancy;
use Tests\Concerns\ProvidesModels;
use Tests\Concerns\RefreshesDatabase;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AuthenticationTest extends TestCase
{
    use InteractsWithTenancy,
        RefreshesDatabase,
        ProvidesModels;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setUpTenancy();
    }

    /**
     * @test
     */
    public function shouldCacheValidUser()
    {
        $auth = \App::make(Authentication::class);
        $demoUser = $this->provideDemoAuthUser();

        $auth->user($demoUser['user_id']);

        $user = $this->users()->find(1);

        $this->assertNotEmpty($user);
        $this->assertEquals($user['auth0'], $demoUser['user_id']);
    }

    /**
     * @return array
     */
    private function provideDemoAuthUser() : array
    {
        return \GuzzleHttp\json_decode(<<<JSON
  {
    "email": "demo@sureclaims.localhost",
    "email_verified": false,
    "user_id": "auth0|5b0e92fa42f10e18ba76e26e",
    "picture": "https://s.gravatar.com/avatar/892f2514a71748f7edce45ea6eaf99c1?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fde.png",
    "nickname": "demo",
    "identities": [
        {
            "user_id": "5b0e92fa42f10e18ba76e26e",
            "provider": "auth0",
            "connection": "sureclaims-localhost",
            "isSocial": false
        }
    ],
    "updated_at": "2018-06-04T19:35:37.594Z",
    "created_at": "2018-05-30T12:03:06.298Z",
    "name": "demo@sureclaims.localhost",
    "app_metadata": {
        "authorization": {
            "groups": [],
            "roles": [],
            "permissions": []
        }
    },
    "last_ip": "180.191.126.182",
    "last_login": "2018-03-15T16:28:06.134Z",
    "logins_count": 10,
    "blocked_for": [],
    "guardian_authenticators": []
}
JSON
        , true);

    }
}
